from __future__ import annotations

from app.tool_catalog.models import ToolFamily

REQUIRED_FAMILY_IDS = [
    'network_discovery',
    'service_fingerprinting',
    'smb_enumeration',
    'ldap_ad_enumeration',
    'kerberos_review',
    'adcs_review',
    'bloodhound_analysis',
    'web_surface_review',
    'vulnerability_analysis',
    'credential_exposure_review',
    'coercion_capture_review',
    'remote_management_review',
    'mssql_review',
    'rdp_review',
    'evidence_reporting',
    'manual_only_sensitive',
]

FAMILIES: dict[str, ToolFamily] = {
    'network_discovery': ToolFamily(
        'network_discovery',
        'Network discovery',
        'Bounded live-host and initial service discovery.',
        'network_discovery',
        'low',
        ['nmap'],
        'safe_auto',
        ['No evasion, no full-port sweep, no arbitrary NSE.'],
    ),
    'service_fingerprinting': ToolFamily(
        'service_fingerprinting',
        'Service fingerprinting',
        'Limited service/version fingerprinting from validated targets.',
        'service_fingerprinting',
        'low',
        ['nmap'],
        'approval_required',
        ['Version checks only; no -A or free-form scripts.'],
    ),
    'smb_enumeration': ToolFamily(
        'smb_enumeration',
        'SMB enumeration',
        'Read-only SMB fingerprinting, signing, and anonymous exposure review.',
        'smb_enumeration',
        'medium',
        ['netexec_smb', 'enum4linux_ng', 'impacket'],
        'approval_required',
        ['No dumping, upload/download, spidering, or command execution.'],
    ),
    'ldap_ad_enumeration': ToolFamily(
        'ldap_ad_enumeration',
        'LDAP/AD enumeration',
        'Read-only domain, users, groups, computers, trusts, and LDAP configuration review.',
        'ldap_kerberos_enumeration',
        'medium',
        ['ldapsearch', 'netexec_ldap', 'bloodyad'],
        'approval_required',
        ['No LDAP writes, password reset, DACL write, or account abuse.'],
    ),
    'kerberos_review': ToolFamily(
        'kerberos_review',
        'Kerberos review',
        'Realm discovery and controlled exposure review from imported or bounded data.',
        'ldap_kerberos_enumeration',
        'high',
        ['kerbrute', 'impacket'],
        'reinforced_approval_required',
        ['No spraying, brute force, cracking, or mass TGS requests.'],
    ),
    'adcs_review': ToolFamily(
        'adcs_review',
        'ADCS review',
        'Certificate services endpoint/template inventory and ESC-path preview.',
        'adcs_review',
        'high',
        ['certipy', 'ldapsearch'],
        'approval_required',
        ['No certificate request exploitation, relay, or coercion chain.'],
    ),
    'bloodhound_analysis': ToolFamily(
        'bloodhound_analysis',
        'BloodHound analysis',
        'Import and analyze existing BloodHound/SharpHound data only.',
        'ad_path_analysis',
        'medium',
        ['bloodhound'],
        'approval_required',
        ['No automatic SharpHound collection.'],
    ),
    'web_surface_review': ToolFamily(
        'web_surface_review',
        'Web surface review',
        'Curated safe web exposure and misconfiguration review.',
        'web_surface_review',
        'medium',
        ['nuclei'],
        'approval_required',
        ['No remote templates, headless/code/fuzzing, AI templates, or exploitation.'],
    ),
    'vulnerability_analysis': ToolFamily(
        'vulnerability_analysis',
        'Vulnerability analysis',
        'Non-destructive vulnerability evidence review and controlled checks.',
        'vulnerability_analysis',
        'high',
        ['nuclei', 'metasploit'],
        'reinforced_approval_required',
        ['Exploit paths stay manual-only/blocked unless separately reviewed.'],
    ),
    'credential_exposure_review': ToolFamily(
        'credential_exposure_review',
        'Credential exposure review',
        'Reporting-only credential exposure summaries from parsed/imported evidence.',
        'credential_exposure_review',
        'high',
        ['reporting', 'bloodhound', 'gmsadumper', 'donpapi'],
        'approval_required',
        ['No active dumping or automated credential collection.'],
    ),
    'coercion_capture_review': ToolFamily(
        'coercion_capture_review',
        'Coercion/capture review',
        'Preview/analyze coercion and capture posture without active poisoning.',
        'coercion_capture_review',
        'high',
        ['coercer', 'responder'],
        'reinforced_approval_required',
        ['No active capture, poisoning, relay, or mass coercion.'],
    ),
    'remote_management_review': ToolFamily(
        'remote_management_review',
        'Remote management review',
        'WinRM/WMI exposure and authentication-surface review.',
        'remote_management_review',
        'medium',
        ['netexec_winrm', 'nmap'],
        'approval_required',
        ['No Evil-WinRM, WMI execution, screenshots, or spraying.'],
    ),
    'mssql_review': ToolFamily(
        'mssql_review',
        'MSSQL review',
        'MSSQL exposure and auth surface review.',
        'mssql_review',
        'medium',
        ['netexec_mssql', 'nmap'],
        'approval_required',
        ['No xp_cmdshell, upload/download, or command execution.'],
    ),
    'rdp_review': ToolFamily(
        'rdp_review',
        'RDP review',
        'RDP exposure, NLA, and TLS review from services/config data.',
        'rdp_review',
        'medium',
        ['nmap'],
        'approval_required',
        ['No screenshots, login attempts, or spraying.'],
    ),
    'evidence_reporting': ToolFamily(
        'evidence_reporting',
        'Evidence/reporting',
        'Parsing, summaries, and reporting from stored evidence.',
        'reporting',
        'low',
        ['reporting', 'evidence'],
        'safe_auto',
        ['No external tool launch.'],
    ),
    'manual_only_sensitive': ToolFamily(
        'manual_only_sensitive',
        'Manual-only sensitive',
        'Explicitly non-executable sensitive techniques for visibility.',
        'manual_only_sensitive',
        'critical',
        ['mimikatz', 'lsass_dump', 'secretsdump', 'password_spray'],
        'manual_only',
        ['Never executable by OpenAD-Zero automation.'],
    ),
}
