import {motion} from 'motion/react';
import type {PentestAction,OperatorApproval} from '../../lib/v2PentestApi';
import {EmptyState} from './EmptyState';
import {ExecutionModeBadge} from './ExecutionModeBadge';
import {SeverityBadge} from './SeverityBadge';
import {StatusBadge} from './StatusBadge';

const riskRank:Record<string,number>={critical:4,high:3,medium:2,low:1};
const statusRank=(a:PentestAction,ap?:OperatorApproval)=>{if(ap?.status==='pending'||a.status==='waiting_approval')return 0;if(a.risk_level==='high'||a.risk_level==='critical')return 1;if(a.status==='blocked'||a.missing_inputs?.length)return 2;if(a.status==='proposed')return 3;if(ap?.status==='approved'||a.status==='approved')return 4;if(['completed','rejected'].includes(a.status)||ap?.status==='rejected')return 5;return 6};
const timeLeft=(expires?:string|null)=>{if(!expires)return '';const ms=new Date(expires).getTime()-Date.now();if(ms<=0)return 'expired';const mins=Math.ceil(ms/60000);return `${mins}m remaining`};
function ApprovalBadge({approval,action}:{approval?:OperatorApproval;action:PentestAction}){const status=approval?.status;let label='';let cls='bg-slate-50 text-slate-600 ring-slate-200';if(status==='pending'){label='Approval pending';cls='bg-amber-50 text-amber-700 ring-amber-200'}else if(status==='approved'){label='Approved';cls='bg-emerald-50 text-emerald-700 ring-emerald-200'}else if(status==='rejected'){label='Rejected';cls='bg-red-50 text-red-700 ring-red-200'}else if(status==='expired'){label='Expired';cls='bg-orange-50 text-orange-700 ring-orange-200'}else if(status==='blocked'||action.status==='blocked'){label='Blocked';cls='bg-slate-100 text-slate-700 ring-slate-300'};return <>{label&&<span className={`rounded-full px-2.5 py-1 text-xs font-semibold ring-1 ${cls}`}>{label}</span>}{status==='approved'&&<span className="rounded-full bg-cyan-50 px-2.5 py-1 text-xs font-semibold text-cyan-700 ring-1 ring-cyan-200">Ready for future execution</span>}{approval?.approval_level==='reinforced'&&<span className="rounded-full bg-rose-50 px-2.5 py-1 text-xs font-semibold text-rose-700 ring-1 ring-rose-200">requires reinforced approval</span>}{approval?.expires_at&&status==='pending'&&<span className="rounded-full bg-slate-50 px-2.5 py-1 text-xs font-semibold text-slate-600 ring-1 ring-slate-200">{timeLeft(approval.expires_at)}</span>}</>}
export function ActionQueue({actions,approvals,onReview,onPrepare,onReject,onApprove}:{actions:PentestAction[];approvals:OperatorApproval[];onReview:(a:PentestAction)=>void;onPrepare:(a:PentestAction)=>void;onReject:(a:PentestAction)=>void;onApprove:(a:PentestAction)=>void}){if(!actions.length)return <EmptyState title="No recommended actions yet" description="Run discovery or recompute the pentest state to populate the action queue."/>;const approvalFor=(a:PentestAction)=>approvals.find(ap=>ap.action_id===a.id);const sorted=[...actions].sort((a,b)=>statusRank(a,approvalFor(a))-statusRank(b,approvalFor(b))||((riskRank[b.risk_level]||0)-(riskRank[a.risk_level]||0))||a.priority-b.priority);return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950">Action Queue</h2><div className="mt-4 space-y-3">{sorted.map((a,i)=>{const ap=approvalFor(a);return <motion.article key={a.id||a.dedupe_key||i} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.18,delay:i*.025}} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><h3 className="font-semibold text-slate-950">{a.title}</h3><p className="mt-1 text-sm text-slate-500">{a.reason}</p><div className="mt-3 flex flex-wrap gap-2"><SeverityBadge severity={a.risk_level}/><ExecutionModeBadge mode={a.execution_mode}/><StatusBadge status={a.status}/><ApprovalBadge approval={ap} action={a}/><span className="rounded-full bg-slate-50 px-2.5 py-1 text-xs font-semibold text-slate-600 ring-1 ring-slate-200">priority {a.priority}</span></div><p className="mt-2 text-xs text-slate-500">{a.phase_id} · {a.tool_id} · {a.template_id}</p>{a.missing_inputs?.length>0&&<p className="mt-2 text-xs text-amber-700">Missing inputs: {a.missing_inputs.join(', ')}</p>}</div><div className="flex shrink-0 flex-wrap gap-2"><button className="btn" onClick={()=>onReview(a)}>Review</button><button className="btn" disabled={a.status==='blocked'||a.execution_mode==='manual_only'||ap?.status==='pending'||ap?.status==='approved'} onClick={()=>onPrepare(a)}>Prepare approval</button>{ap?.status==='pending'&&<button className="rounded-lg px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50" onClick={()=>onReject(a)}>Reject</button>}{ap?.status==='pending'&&<button className="btn" onClick={()=>onApprove(a)}>Approve</button>}<button className="rounded-lg bg-slate-100 px-3 py-2 text-sm font-semibold text-slate-400" disabled title="Run endpoint not implemented yet">Approve & Run</button></div></div></motion.article>})}</div></section>}
