import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Boxes,CheckCircle2,XCircle} from 'lucide-react';
import {getToolCatalog,getToolReadiness,type ToolCatalog,type ToolReadiness} from '../../lib/v2ToolCatalogApi';

const riskClass=(risk:string)=>risk==='critical'||risk==='high'?'bg-rose-50 text-rose-700 ring-rose-200':risk==='medium'?'bg-amber-50 text-amber-700 ring-amber-200':'bg-emerald-50 text-emerald-700 ring-emerald-200';

export function ToolCatalogPanel(){
  const [catalog,setCatalog]=useState<ToolCatalog|null>(null),[readiness,setReadiness]=useState<ToolReadiness[]>([]),[error,setError]=useState('');
  useEffect(()=>{let active=true;Promise.all([getToolCatalog(),getToolReadiness()]).then(([c,r])=>{if(active){setCatalog(c);setReadiness(r)}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Tool catalog unavailable')});return()=>{active=false}},[]);
  const ready=useMemo(()=>new Map(readiness.map(r=>[r.tool_id,r])),[readiness]);
  const supported=catalog?.templates.filter(t=>t.supported_for_run)||[];
  const guarded=catalog?.templates.filter(t=>!t.supported_for_run&&(t.execution_mode==='manual_only'||t.execution_mode==='blocked')).slice(0,12)||[];
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-semibold text-slate-950"><Boxes size={18}/> Tool Catalog / Tool Readiness</h2><p className="mt-1 text-sm text-slate-500">Read-only catalogue view. This panel does not start tools or expose any run control.</p></div></div>{error&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800"><AlertTriangle className="mr-2 inline" size={16}/>Tool catalog endpoint unavailable: {error}</p>}{catalog&&<div className="mt-4 grid gap-4 xl:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm font-semibold text-slate-900">Families</p><p className="mt-2 text-3xl font-bold text-slate-950">{catalog.families.length}</p><div className="mt-3 flex flex-wrap gap-2">{catalog.families.slice(0,8).map(f=><span key={f.id} className="rounded-full bg-white px-2.5 py-1 text-xs font-semibold text-slate-600 ring-1 ring-slate-200">{f.id}</span>)}</div></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm font-semibold text-slate-900">Supported run templates</p><p className="mt-2 text-3xl font-bold text-slate-950">{supported.length}</p><div className="mt-3 space-y-1">{supported.map(t=><p key={t.template_id} className="text-xs text-slate-600">{t.template_id}</p>)}</div></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm font-semibold text-slate-900">Manual/blocked samples</p><p className="mt-2 text-3xl font-bold text-slate-950">{catalog.templates.filter(t=>t.execution_mode==='manual_only'||t.execution_mode==='blocked').length}</p><div className="mt-3 space-y-1">{guarded.map(t=><p key={t.template_id} className="text-xs text-slate-600">{t.template_id}</p>)}</div></div></div>}{readiness.length>0&&<div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{readiness.slice(0,12).map(r=><article key={r.tool_id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-start justify-between gap-2"><div><p className="font-semibold text-slate-900">{r.tool_id}</p><p className="text-xs text-slate-500">{r.binary||'internal'} · {r.integration_status}</p></div>{r.available?<CheckCircle2 className="text-emerald-600" size={18}/>:<XCircle className="text-slate-400" size={18}/>}</div>{r.missing_reason&&<p className="mt-2 text-xs text-amber-700">{r.missing_reason}</p>}<div className="mt-2 flex flex-wrap gap-1">{Object.entries(r.risk_summary).map(([risk,count])=><span key={risk} className={`rounded-full px-2 py-0.5 text-[11px] font-semibold ring-1 ${riskClass(risk)}`}>{risk}: {count}</span>)}</div><p className="mt-2 text-xs text-slate-500">Supported: {r.supported_templates.length} · Guarded: {r.blocked_templates.length}</p></article>)}</div>}</section>
}
